<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>rule1</name>
  <uuid>0cc0356d-887a-4978-9168-7ef5c0e4483c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the First Name of FirstNameSpace is "ABC"
then
	set decision to "hello " + the First Name ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
